sudo: required

services:
  - docker

before_install:
  - dokcer build -t conradmugabe/sports-betting-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true conradmugabe/sports-betting npm run test

after_success:
  - docker build -t conradmugabe/sports-betting-client ./client
  - docker build -t conradmugabe/sports-betting-nginx ./nginx

  # push docker images to docker hub
  - docker push conradmugabe/sports-betting-client
  - docker push conradmugabe/sports-betting-nginx