version: "3.9"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - ./node_modules
  api:
    build:
      context: ./odds
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/venv
      - ./odds:/app/
